[FIX] purchase_order_product_recommendation: fix abs missing error
When this condition was reached, it failed with:

    EvaluationError: Name 'abs' is not defined

Fixes https://github.com/OCA/purchase-workflow/issues/2052
@moduon MT-3581