[FIX] purchase_security: fix invalid res.users kanban view
Fixes
```
Error: Missing 'card' template.
```
when opening the purchase team form view.

[UPD] Update purchase_security.pot

[BOT] post-merge updates

Update translation files

Updated by "Update PO files to match POT (msgmerge)" hook in Weblate.

Translation: purchase-workflow-18.0/purchase-workflow-18.0-purchase_security
Translate-URL: https://translation.odoo-community.org/projects/purchase-workflow-18-0/purchase-workflow-18-0-purchase_security/