[FIX] purchase_*_discount: Post-install test + fallback to load CoA + assert almost
Since odoo/odoo@d0342c8, the default existing company is not getting a
CoA automatically, provoking than the current tests fail with error:

odoo.exceptions.UserError: No journal could be found in company My Company (San Francisco) for any of those types: purchase

provoked by the lack of a CoA installed.

Thus, we put tests post-install for being sure localization modules are
installed, the same as AccountTestInvoicingCommon does, but we don't
inherit from it, as it creates an overhead creating 2 new companies and
loading their CoA, and some more stuff, while we don't need all of that.

Besides, if you don't have `l10n_generic_coa` installed, you can't use
another CoA (like `l10n_es`) easily, so we put little code to select the
first available CoA.

It also includes a change on the assert for avoiding rounding issues
discovered while testing this one.